FROM node:18

WORKDIR /app

COPY package*.json ./
COPY insert.js ./
COPY categories_img.js ./
COPY Data ./Data
COPY wait-for-postgres.sh ./wait-for-postgres.sh

RUN chmod +x wait-for-postgres.sh && npm install pg

CMD ["./wait-for-postgres.sh"]
