name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main # Déclenchement sur push sur la branche main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Configurer Docker (Docker Buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Nom d'utilisateur Docker Hub dans les secrets 
          password: ${{ secrets.DOCKER_PASSWORD }} # Mot de passe Docker Hub dans les secrets 

      # Étape 4 : Construire l'image Docker
      - name: Build Docker image
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}  
          export GITHUB_SHA=$(git rev-parse --short HEAD)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/greenroots-pg:${{ github.sha }}  -f Postgres/Dockerfile Postgres

      # Étape 5 : Pousser l'image vers Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/greenroots-pg:${{ github.sha }}

      # Étape 6: Déconnexion de Docker 
      - name: Logout from DockerHub
        run: docker logout

      # Étape 7 : Se connecter au VPS via SSH et déployer
      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_IP }} # IP de votre VPS Hostinger dans les secrets
          key: ${{ secrets.HOSTINGER_SSH_KEY }} # Clé SSH privée (doit être ajoutée dans les secrets)
          script: |
            /opt/deployment/deploy-bd.sh ${{ secrets.DOCKER_USERNAME }}/greenroots-pg postgres 5432 ${{ github.sha }}